### ISSUE TITLE
Error: Value for unconfigurable attribute

### ISSUE THREAD

**Issue by diamondH123** [AdminTurnedDevOps/DevOps-The-Hard-Way-AWS#9]
![Screen Shot 2022-02-19 at 8 06 52 PM](https://user-images.githubusercontent.com/98285127/154825607-16b58951-1716-4ef5-886f-f094f4b28e0c.png)

**Comment by jconnor0426** [comment]
Hashicorp recently updated how they handle the AWS s3 buckets. 

You can fix this by adding a version to the AWS provider. Sourced solution from [here](https://github.com/hashicorp/terraform-provider-aws/issues/23125#issuecomment-1036412659)

So that it looks like this: 
```
provider "aws" {
  region = "us-east-2"
  version = "~> 3.74"
}
```

Later on you'll have to update the other sections to specify the new version as well: 
```
aws = {
      source = "hashicorp/aws"
      version = "~> 3.74"
    }
```
